all:
  hosts:
    kub-1:
      ansible_user: vagrant
      ansible_host: 192.168.56.1
      ansible_port: 2222
      ansible_ssh_private_key_file: '../.vagrant.d/insecure_private_keys/vagrant.key.rsa'

      ip: 192.168.56.101
    kub-2:
      ansible_user: vagrant
      ansible_host: 192.168.56.1
      ansible_port: 2200
      ansible_ssh_private_key_file: '../.vagrant.d/insecure_private_keys/vagrant.key.rsa'

      ip: 192.168.56.102
    kub-3:
      ansible_user: vagrant
      ansible_host: 192.168.56.1
      ansible_port: 2201
      ansible_ssh_private_key_file: '../.vagrant.d/insecure_private_keys/vagrant.key.rsa'

      ip: 192.168.56.103
  children:
    kube_control_plane:
      hosts:
        kub-1:
        kub-2:
    kube_node:
      hosts:
        kub-1:
        kub-2:
        kub-3:
    etcd:
      hosts:
        kub-1:
        kub-2:
        kub-3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
