certmanager:
  install: false
  installCRDs: false
registry:
  hpa:
    minReplicas: 1
    maxReplicas: 3
  ingress:
    tls:
      secretName: http-tls-registry
gitlab:
  migrations:
    enabled: true

  gitlab-shell:
    minReplicas: 1
    maxReplicas: 3
  sidekiq:
    minReplicas: 1
    maxReplicas: 3

    hpa:
      cpu:
        targetAverageValue: 600m
  gitaly:
    persistence:
      size: 10Gi
  kas:
    minReplicas: 1
    maxReplicas: 3
    ingress:
      tls:
        secretName: http-tls-kas
  webservice:
    hpa:
      minReplicas: 1
      maxReplicas: 3
    ingress:
      tls:
        secretName: http-tls-gitlab


gitlab-runner:
  install: false

global:
  appConfig:
    object_store:
      connection:
        key: connection
        secret: gitlab-rails-storage
        # spec:
        #   connection: |
        #       # Example configuration of `connection` secret for Rails
        #       # Example for Minio storage
        #       #   See https://gitlab.com/gitlab-org/charts/gitlab/blob/master/doc/charts/globals.md#connection
        #       #   See https://gitlab.com/gitlab-org/charts/gitlab/blob/master/doc/advanced/external-object-storage
        #       provider: AWS
        #       # Specify the region
        #       region: us-east-1
        #       # Specify access/secret keys
        #       aws_access_key_id: xxxxxxxxxx
        #       aws_secret_access_key: xxxxxxxxxxxxxxxxxxx
        #       # The below settings are for S3 compatible endpoints
        #       #   See https://docs.gitlab.com/ee/administration/job_artifacts.html#s3-compatible-connection-settings
        #       aws_signature_version: 4
        #       host: minio.example.com
        #       endpoint: "https://minio.example.com"
        #       path_style: true

      enabled: true
      proxy_download: false
    omniauth:
      allowBypassTwoFactor: null
      allowSingleSignOn:
        - openid_connect
      autoLinkUser: true
      autoSignInWithProvider: null
      blockAutoCreatedUsers: true
      enabled: true
      providers:
        - secret: omniauth-example-keycloak
        # spec:
        #   provider: |
        #     name: "openid_connect" # do not change this parameter
        #     label: "example Keycloak" # optional label for login button, defaults to "Openid Connect"
        #     args:
        #       name: "openid_connect"
        #       scope: ["openid", "profile", "email"]
        #       response_type: "code"
        #       issuer:  "https://keycloak.example.com/realms/example"
        #       client_auth_method: "query"
        #       discovery: true
        #       uid_field: "preferred_username"
        #       pkce: true
        #       client_options:
        #         identifier: "gitlab"
        #         secret: "xxxxxxxxxxxxxxxxxxx"
        #         redirect_uri: "https://gitlab.repo.example.com/users/auth/openid_connect/callback"


  cattle:
    clusterId: local
    clusterName: example
    rkePathPrefix: ''
    rkeWindowsPathPrefix: ''
    systemProjectId: p-hmjcp
    url: https://rancher.example.com
  edition: ce
  email:
    from: no-reply@example.com
    reply_to: no-reply@example.com
  gitlabVersion: 16.7.3
  hosts:
    domain: repo.example.com
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: le-http-auth
    class: nginx
    configureCertmanager: false
  minio:
    enabled: false
  shell:
    port: 30222
  smtp:
    address: smtp.yandex.com
    authentication: login
    enabled: true
    password:
      secret: no-reply-password
      # spec:
      #   password: xxxxxxxxxx

    port: 465
    tls: true
    user_name: no-reply@example.com

nginx-ingress:
  enabled: false
prometheus:
  install: false
