apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
scheduler:
  name: ''

spec:
  configuration:
    name: minio-env-configuration
  credsSecret:
    name: minio-secret
  env:
  - name: MINIO_PROMETHEUS_URL
    value: http://rancher-monitoring-prometheus.cattle-monitoring-system:9090
  - name: MINIO_PROMETHEUS_JOB_ID
    value: minio-tenants/minio-pool
  exposeServices:
    console: true
    minio: true
  features:
    domains:
      console: https://minio-console-cloud.example.com
      minio:
      - https://minio-cloud.example.com
  image: minio/minio:RELEASE.2023-10-25T06-33-25Z
  imagePullPolicy: IfNotPresent
  imagePullSecret: {}
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  -
    name: pool-0
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 1Gi
    runtimeClassName: ""
    servers: 4
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 250Gi
        storageClassName: manual-local
      status: {}
    volumesPerServer: 1
  prometheusOperator: true
  requestAutoCert: false
  serviceAccountName: minio-sa
  users:
  - name: minio-user-0

